name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: submodule init
      run: git submodule update --init --recursive
    - name: apt-get
      run: sudo apt-get update && sudo apt-get install -y build-essential clang-7 llvm-7 libelf-dev python3 python3-pip libcmocka-dev lcov
    - name: make
      run: make
    - name: make test
      run: make run_unittests
